version = 0.1

[default.deploy.parameters]
stack_name = "FintechPulseIAC"
region = "us-east-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nlkkjwk9s9n3"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
resolve_s3 = true
s3_prefix = "FintechPulseIAC"
image_repositories = []

